[aardio æ–‡æ¡£](../../../index.htm "aardio ç¼–ç¨‹è¯­è¨€æ–‡æ¡£é¦–é¡µ")

# aardio èŒƒä¾‹: è°ƒç”¨ AutoCAD - å¯¹è±¡æ•°ç»„

```aardio aardio
//aardio è°ƒç”¨ AutoCAD - å¯¹è±¡æ•°ç»„
import com.cad
var cad = com.cad();
cad.Visible = true;

var patternName = "ANSI31";//å¡«å……å›¾æ¡ˆçš„åç§?var patternType = 0 ;// å¡«å……ç±»å‹

//åœ¨æ¨¡å‹ç©ºé—´ä¸­æ·»åŠ å¡«å……å›¾æ¡ˆå¯¹è±¡ï¼ˆHatchï¼?var hatchObj = cad.ActiveDocument.ModelSpace.AddHatch(patternType, patternName, true);

//å®šä¹‰åœ†å¿ƒå’ŒåŠå¾?var centerPoint = {0;0;0};
var radius = 1;

//åˆ›å»ºåœ†å¯¹è±?var circle = cad.ActiveDocument.ModelSpace.AddCircle(centerPoint, radius);

/*
å¦‚æœæ•°ç»„æˆå‘˜ä¸ºæ™®é€?COM å¯¹è±¡ï¼ˆIDispatch å¯¹è±¡ï¼‰ï¼Œåœ?COM æ¥å£ä¸­è‡ªåŠ¨è½¬æ¢ä¸º VT_DISPATCH ç±»å‹ SafeArrayã€?ç»†èŠ‚è¯·å‚è€ƒã€Œaardio èŒƒä¾‹ / COM ç»„ä»¶ / è¿›é˜¶æç¤º / ç±»å‹è½¬æ¢è§„åˆ™ã€?*/
var outerLoop = { circle };

//æ·»åŠ ä¸€ä¸ªåœ†ä½œä¸ºå¡«å……å›¾æ¡ˆçš„å¤–å¾ªç¯è¾¹ç•Œ
hatchObj.AppendOuterLoop (  outerLoop );

//è®¡ç®—å¹¶æ›´æ–°å¡«å……å›¾æ¡?hatchObj.Evaluate();

//é‡æ–°ç”Ÿæˆè§†å›¾
cad.ActiveDocument.Regen(cad.acActiveViewport);

```

[Markdown æ ¼å¼](https://www.aardio.com/zh-cn/doc/example/COM/AutoCAD/dispArray.md)

